a=10
b=5
print("The value of a=",a)
print("The value of b=",b)
print("The value of a before swapping=",a)
print("The value of b before swapping=",b)
temp=a
a=b
b=temp
print("The value of a after swapping=",a)
print("The value of b after swapping=",b)
a=10
b=5
a=a+b
b=a-b
a=a-b
print("The value of a after swapping=",a)
print("The value of b after swapping=",b)
